// GET /api/directory
export const GET_DIRECTORIES_REQUEST = "GET_DIRECTORIES_REQUEST";
export const GET_DIRECTORIES_SUCCESS = "GET_DIRECTORIES_SUCCESS";
export const GET_DIRECTORIES_FAIL = "GET_DIRECTORIES_FAIL";

// GET /api/directory/:username
export const GET_DIRECTORY_REQUEST = "GET_DIRECTORY_REQUEST";
export const GET_DIRECTORY_SUCCESS = "GET_DIRECTORY_SUCCESS";
export const GET_DIRECTORY_FAIL = "GET_DIRECTORY_FAIL";

// GET /api/directory/products/:id
export const GET_DIRECTORY_PRODUCTS_REQUEST = "GET_DIRECTORY_PRODUCTS_REQUEST";
export const GET_DIRECTORY_PRODUCTS_SUCCESS = "GET_DIRECTORY_PRODUCTS_SUCCESS";
export const GET_DIRECTORY_PRODUCTS_FAIL = "GET_DIRECTORY_PRODUCTS_FAIL";

// GET /api/directory/services/:id
export const GET_DIRECTORY_SERVICES_REQUEST = "GET_DIRECTORY_SERVICES_REQUEST";
export const GET_DIRECTORY_SERVICES_SUCCESS = "GET_DIRECTORY_SERVICES_SUCCESS";
export const GET_DIRECTORY_SERVICES_FAIL = "GET_DIRECTORY_SERVICES_FAIL";

// POST /api/directory/review/:username
export const REVIEW_DIRECTORY_REQUEST = "REVIEW_DIRECTORY_REQUEST";
export const REVIEW_DIRECTORY_SUCCESS = "REVIEW_DIRECTORY_SUCCESS";
export const REVIEW_DIRECTORY_FAIL = "REVIEW_DIRECTORY_FAIL";

// DEL /api/directory/review/remove/:username
export const REMOVE_DIRECTORY_REVIEW_REQUEST = "REMOVE_DIRECTORY_REVIEW_REQUEST";
export const REMOVE_DIRECTORY_REVIEW_SUCCESS = "REMOVE_DIRECTORY_REVIEW_SUCCESS";
export const REMOVE_DIRECTORY_REVIEW_FAIL = "REMOVE_DIRECTORY_REVIEW_FAIL";

/*
 * Admin actions
 */

// GET /api/directory/all
export const GET_ALL_DIRECTORIES_REQUEST = "GET_ALL_DIRECTORIES_REQUEST";
export const GET_ALL_DIRECTORIES_SUCCESS = "GET_ALL_DIRECTORIES_SUCCESS";
export const GET_ALL_DIRECTORIES_FAIL = "GET_ALL_DIRECTORIES_FAIL";

// GET /api/directory/any/:id
export const GET_ANY_DIRECTORY_REQUEST = "GET_ANY_DIRECTORY_REQUEST";
export const GET_ANY_DIRECTORY_SUCCESS = "GET_ANY_DIRECTORY_SUCCESS";
export const GET_ANY_DIRECTORY_FAIL = "GET_ANY_DIRECTORY_FAIL";

// POST /api/directory/add
export const ADD_DIRECTORY_REQUEST = "ADD_DIRECTORY_REQUEST";
export const ADD_DIRECTORY_SUCCESS = "ADD_DIRECTORY_SUCCESS";
export const ADD_DIRECTORY_FAIL = "ADD_DIRECTORY_FAIL";
export const ADD_DIRECTORY_RESET = "ADD_DIRECTORY_RESET";

// PUT /api/directory/edit/:id
export const EDIT_DIRECTORY_REQUEST = "EDIT_DIRECTORY_REQUEST";
export const EDIT_DIRECTORY_SUCCESS = "EDIT_DIRECTORY_SUCCESS";
export const EDIT_DIRECTORY_FAIL = "EDIT_DIRECTORY_FAIL";
export const EDIT_DIRECTORY_RESET = "EDIT_DIRECTORY_RESET";

// PUT /api/directory/approve/:id
export const APPROVE_DIRECTORY_REQUEST = "APPROVE_DIRECTORY_REQUEST";
export const APPROVE_DIRECTORY_SUCCESS = "APPROVE_DIRECTORY_SUCCESS";
export const APPROVE_DIRECTORY_FAIL = "APPROVE_DIRECTORY_FAIL";

// DEL /api/directory/remove/:id
export const REMOVE_DIRECTORY_REQUEST = "REMOVE_DIRECTORY_REQUEST";
export const REMOVE_DIRECTORY_SUCCESS = "REMOVE_DIRECTORY_SUCCESS";
export const REMOVE_DIRECTORY_FAIL = "REMOVE_DIRECTORY_FAIL";
export const REMOVE_DIRECTORY_RESET = "REMOVE_DIRECTORY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
