// GET /api/directory
export const GET_DIRECTORIES_REQUEST = "GET_DIRECTORIES_REQUEST";
export const GET_DIRECTORIES_SUCCESS = "GET_DIRECTORIES_SUCCESS";
export const GET_DIRECTORIES_FAIL = "GET_DIRECTORIES_FAIL";

// GET /api/directory/:username
export const GET_DIRECTORY_REQUEST = "GET_DIRECTORY_REQUEST";
export const GET_DIRECTORY_SUCCESS = "GET_DIRECTORY_SUCCESS";
export const GET_DIRECTORY_FAIL = "GET_DIRECTORY_FAIL";
