/*
 * Public Actions
 */

// GET /api/product
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

// GET /api/product/:id
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

/*
 * Client Actions
 */

// GET /api/product/own
export const GET_OWN_PRODUCTS_REQUEST = "GET_OWN_PRODUCTS_REQUEST";
export const GET_OWN_PRODUCTS_SUCCESS = "GET_OWN_PRODUCTS_SUCCESS";
export const GET_OWN_PRODUCTS_FAIL = "GET_OWN_PRODUCTS_FAIL";

// GET /api/product/own/:id
export const GET_OWN_PRODUCT_REQUEST = "GET_OWN_PRODUCT_REQUEST";
export const GET_OWN_PRODUCT_SUCCESS = "GET_OWN_PRODUCT_SUCCESS";
export const GET_OWN_PRODUCT_FAIL = "GET_OWN_PRODUCT_FAIL";

// POST /api/product/add
export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_RESET = "ADD_PRODUCT_RESET";

// PUT /api/product/edit/:id
export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";
export const EDIT_PRODUCT_RESET = "EDIT_PRODUCT_RESET";

// DEL /api/product/remove/:id
export const REMOVE_PRODUCT_REQUEST = "REMOVE_PRODUCT_REQUEST";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
export const REMOVE_PRODUCT_FAIL = "REMOVE_PRODUCT_FAIL";
export const REMOVE_PRODUCT_RESET = "REMOVE_PRODUCT_RESET";

/*
 * Review and question actions
 */

// POST /api/product/review/:id
export const REVIEW_PRODUCT_REQUEST = "REVIEW_PRODUCT_REQUEST";
export const REVIEW_PRODUCT_SUCCESS = "REVIEW_PRODUCT_SUCCESS";
export const REVIEW_PRODUCT_FAIL = "REVIEW_PRODUCT_FAIL";

// DEL /api/product/review/remove/:id
export const REMOVE_PRODUCT_REVIEW_REQUEST = "REMOVE_PRODUCT_REVIEW_REQUEST";
export const REMOVE_PRODUCT_REVIEW_SUCCESS = "REMOVE_PRODUCT_REVIEW_SUCCESS";
export const REMOVE_PRODUCT_REVIEW_FAIL = "REMOVE_PRODUCT_REVIEW_FAIL";

// POST /api/product/question/:id
export const QUESTION_PRODUCT_REQUEST = "QUESTION_PRODUCT_REQUEST";
export const QUESTION_PRODUCT_SUCCESS = "QUESTION_PRODUCT_SUCCESS";
export const QUESTION_PRODUCT_FAIL = "QUESTION_PRODUCT_FAIL";

// DEL /api/product/question/remove/:id
export const REMOVE_PRODUCT_QUESTION_REQUEST = "REMOVE_PRODUCT_QUESTION_REQUEST";
export const REMOVE_PRODUCT_QUESTION_SUCCESS = "REMOVE_PRODUCT_QUESTION_SUCCESS";
export const REMOVE_PRODUCT_QUESTION_FAIL = "REMOVE_PRODUCT_QUESTION_FAIL";

// POST /api/product/answer/:id/:qid
export const ANSWER_PRODUCT_REQUEST = "ANSWER_PRODUCT_REQUEST";
export const ANSWER_PRODUCT_SUCCESS = "ANSWER_PRODUCT_SUCCESS";
export const ANSWER_PRODUCT_FAIL = "ANSWER_PRODUCT_FAIL";

// DEL /api/product/answer/remove/:id/:qid
export const REMOVE_PRODUCT_ANSWER_REQUEST = "REMOVE_PRODUCT_ANSWER_REQUEST";
export const REMOVE_PRODUCT_ANSWER_SUCCESS = "REMOVE_PRODUCT_ANSWER_SUCCESS";
export const REMOVE_PRODUCT_ANSWER_FAIL = "REMOVE_PRODUCT_ANSWER_FAIL";

/*
 * Admin actions
 */

// GET /api/product/all
export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

// GET /api/product/any/:id
export const GET_ANY_PRODUCT_REQUEST = "GET_ANY_PRODUCT_REQUEST";
export const GET_ANY_PRODUCT_SUCCESS = "GET_ANY_PRODUCT_SUCCESS";
export const GET_ANY_PRODUCT_FAIL = "GET_ANY_PRODUCT_FAIL";

// PUT /api/product/approve/:id
export const APPROVE_PRODUCT_REQUEST = "APPROVE_PRODUCT_REQUEST";
export const APPROVE_PRODUCT_SUCCESS = "APPROVE_PRODUCT_SUCCESS";
export const APPROVE_PRODUCT_FAIL = "APPROVE_PRODUCT_FAIL";

// Clear errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
